# Generated by Django 3.2.20 on 2023-08-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230804_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
